# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/HDL/dt555w_constraints.xdc

# IP: ip/FlashPageMemory/FlashPageMemory.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FlashPageMemory || ORIG_REF_NAME==FlashPageMemory} -quiet] -quiet

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/TestBram/TestBram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TestBram || ORIG_REF_NAME==TestBram} -quiet] -quiet

# IP: ip/FTDI_FIFOs/FTDI_FIFOs.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FTDI_FIFOs || ORIG_REF_NAME==FTDI_FIFOs} -quiet] -quiet

# IP: ip/FTDI_FIFO_AW/FTDI_FIFO_AW.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FTDI_FIFO_AW || ORIG_REF_NAME==FTDI_FIFO_AW} -quiet] -quiet

# IP: ip/fast_clock/fast_clock.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fast_clock || ORIG_REF_NAME==fast_clock} -quiet] -quiet

# IP: ip/DTClockGenerator/DTClockGenerator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DTClockGenerator || ORIG_REF_NAME==DTClockGenerator} -quiet] -quiet
